# Build stage
FROM golang:1.23.4 as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ssh-proxy ./cmd/proxy

# Run stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/ssh-proxy .
COPY configs /app/configs
CMD ["./ssh-proxy", "--config", "/app/configs/config.yaml"]
