FROM ubuntu:20.04

# Install OpenSSH server
RUN apt-get update && apt-get install -y openssh-server

RUN mkdir /var/run/sshd

RUN useradd -m -s /bin/bash admin && echo 'admin:admin_password' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
