# Server configuration
server:
  port: 2022
  host_key_path: "./configs/ssh_host_ed25519_key"  # SSH host key

# Upstream SSH server to connect to
upstream:
  host: "ssh-server"  
  port: 22          
  username: "admin"   
  auth:
    type: "password"
    password: "admin_password" 

users:
# example for password auth
  - username: "user1"
    auth:
      type: "password"
      password: "user1pass"
# example for ssh-key based auth
  - username: "keyuser"
    auth:
      type: "publickey"
      key_path: "./configs/authorized_keys"

# Logging configuration
logging:
  directory: "./logs"

# LLM Configuration (optional)
llm:
  enabled: true
  api_key: "openai-api-key"
  provider: "openai"
  model: "gpt-4"
