
server:
  port: 2022
  host_key_path: "configs/host_key"

# Upstream 
upstream:
  host: "upstream"
  port: 2222
  username: "testuser"
  auth:
    type: "password"
    password: "testpassword"

# Users allowed to connect to the proxy
users:
  - username: "user1"
    auth:
      type: "password"
      password: "password1"
  - username: "user2"
    auth:
      type: "publickey"
      key_path: "configs/authorized_keys/user2.pub"

# Logging configuration
logging:
  directory: "logs"

# LLM 
llm:
  enabled: false
  api_key: ""
  provider: "openai"
  model: "gpt-3.5-turbo"
